train_img_path: ./DeepLearning-Basic/Data/MNIST/train-images.idx3-ubyte
train_label_path: ./DeepLearning-Basic/Data/MNIST/train-labels.idx1-ubyte
test_img_path: ./DeepLearning-Basic/Data/MNIST/t10k-images.idx3-ubyte
test_label_path: ./DeepLearning-Basic/Data/MNIST/t10k-labels.idx1-ubyte
train_batch: 128
dev_batch: 128
test_batch: 128
save_path: ./checkpoint
num_classes: 10
patience: 5
model: GoogLeNet # LeNet, AlexNet, VGG, NiN, GoogLeNet
learning_rate: 0.001
num_epochs: 5
best_metric: accuracy # accuracy, f1, precision, recall