train_img_path: ./DeepLearning-Basic/Data/train-images.idx3-ubyte
train_label_path: ./DeepLearning-Basic/Data/train-labels.idx1-ubyte
test_img_path: ./DeepLearning-Basic/Data/t10k-images.idx3-ubyte
test_label_path: ./DeepLearning-Basic/Data/t10k-labels.idx1-ubyte
train_batch: 128
dev_batch: 128
test_batch: 128
save_path: ./checkpoint
image_H: 28
image_W: 28
image_C: 1
num_classes: 10
patience: 5
model: LeNet # LeNet, AlexNet
learning_rate: 0.001
num_epochs: 100
best_metric: accuracy # accuracy, f1, precision, recall